-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIBRfZBXqA73jnAd1egQRlhXXtSV6fWN7Ips3utZNIZL+oAoGCCqGSM49
AwEHoUQDQgAEqHQRAUNWWIixW8qAH4v9sebM4DEnZ+zhhZK/tZX2AR6vyMY82mbe
ozo7Tf7aNq56wm3AwXemFsUYdssWvODprw==
-----END EC PRIVATE KEY-----
