package ninjawar.supporter;

import com.badlogic.gdx.graphics.glutils.ShaderProgram;

public class GrayscaleShader {
    static String fragmentShader = "#ifdef GL_ES\n    precision mediump float;\n#endif\n\nvarying vec4 v_color;\nvarying vec2 v_texCoords;\nuniform sampler2D u_texture;\n\nvoid main() {\n  vec4 c = v_color * texture2D(u_texture, v_texCoords);\n  float grey = (c.r + c.g + c.b) / 3.0;\n  gl_FragColor = vec4(grey, grey, grey, c.a);\n}";
    static String fragmentShader2 = "#ifdef GL_ES\n    precision mediump float;\n#endif\n\nvarying vec4 v_color;\nvarying vec2 v_texCoords;\nuniform sampler2D u_texture;\nuniform vec2 u_texSize;\nuniform vec2 u_velocity;\nuniform float u_blurIntensity;\n\nvoid main() {\n    vec2 texelSize = 1.0 / u_texSize;\n    vec4 color = v_color * texture2D(u_texture, v_texCoords);\n\n    // Motion blur: sample along velocity direction\n    vec4 blur = vec4(0.0);\n    float totalWeight = 0.0;\n    const int samples = 10;\n    vec2 blurDir = normalize(u_velocity) * u_blurIntensity * texelSize;\n    for (int i = -samples / 2; i <= samples / 2; i++) {\n        float weight = exp(-float(i * i) / float(samples));\n        vec2 offset = float(i) * blurDir;\n        blur += weight * texture2D(u_texture, v_texCoords + offset);\n        totalWeight += weight;\n    }\n    blur /= totalWeight;\n\n    // Blend original color with blur for smooth trail\n    vec4 finalColor = mix(color, blur, 0.6);\n\n    // Brighten the color\n    finalColor.rgb *= 1.5;\n\n    // Add a lighter, radiant tint for ethereal glow\n    vec3 tint = vec3(0.95, 0.95, 1.0);\n    finalColor.rgb *= tint;\n\n    // Apply semi-transparency\n    float alpha = 0.5 * color.a;\n\n    gl_FragColor = vec4(finalColor.rgb, alpha);\n}";
    static String vertexShader = "attribute vec4 a_position;\nattribute vec4 a_color;\nattribute vec2 a_texCoord0;\n\nuniform mat4 u_projTrans;\n\nvarying vec4 v_color;\nvarying vec2 v_texCoords;\n\nvoid main() {\n    v_color = a_color;\n    v_texCoords = a_texCoord0;\n    gl_Position = u_projTrans * a_position;\n}";
    static String vertexShader2 = "attribute vec4 a_position;\nattribute vec4 a_color;\nattribute vec2 a_texCoord0;\n\nuniform mat4 u_projTrans;\n\nvarying vec4 v_color;\nvarying vec2 v_texCoords;\n\nvoid main() {\n    v_color = a_color;\n    v_texCoords = a_texCoord0;\n    gl_Position = u_projTrans * a_position;\n}";
    public static ShaderProgram grayscaleShader = new ShaderProgram(vertexShader, fragmentShader);
    public static ShaderProgram motionBlurShader = new ShaderProgram(vertexShader2, fragmentShader2);
}
